  function setEditTool(tool){editTool=tool;pendingLong=null;$$('.edit-tool').forEach(b=>b.classList.toggle('active',b.dataset.editTool===tool));const names={draw:'配置',select:'単選択',range:'範囲選択',eraser:'消しゴム'};$('#editToolName').textContent=names[tool];els.wrap.classList.remove('tool-draw','tool-select','tool-range','tool-eraser');els.wrap.classList.add(`tool-${tool}`);toast(`操作：${names[tool]}`)}
  function createPointFromEvent(e,width=2){const rect=els.wrap.getBoundingClientRect();const x=clamp(e.clientX-rect.left,0,rect.width);const y=clamp(e.clientY-rect.top,0,rect.height);const lane=clamp(Math.round(x/rect.width*LANES-width/2),0,LANES-width);const bottom=rect.height-y;return normalizePoint({tick:bottomToTick(bottom),lane,width})}
  function createNote(type,point,raw=null){pushHistory();let n;if(type==='long'){if(!pendingLong){pendingLong={id:uid(),type:'long',start:deep(point),end:deep(point),rawStart:raw,rawEnd:raw};project.notes.push(pendingLong);selectOnly(pendingLong.id,false);toast('ロング始点を配置しました。終点をクリックしてください');renderAll();scheduleSave();return}else{pendingLong.end=deep(point);pendingLong.rawEnd=raw;normalizeNote(pendingLong);n=pendingLong;pendingLong=null}}else{n={id:uid(),type,tick:point.tick,lane:point.lane,width:point.width,rawTime:raw};project.notes.push(n)}selectOnly(n.id,false);renderAll();scheduleSave()}
  function notePoints(n){return n.type==='long'?[n.start,n.end]:[n]}
  function groupLimits(notes){const pts=notes.flatMap(notePoints);return{minLane:Math.min(...pts.map(p=>p.lane)),maxLane:Math.max(...pts.map(p=>p.lane+p.width)),minTick:Math.min(...pts.map(p=>p.tick)),maxTick:Math.max(...pts.map(p=>p.tick))}}
  function beginErase(){if(!erasing){pushHistory();erasing=true;eraseChanged=false}}
  function eraseById(id){const before=project.notes.length;project.notes=project.notes.filter(n=>n.id!==id);selectedIds.delete(id);if(pendingLong?.id===id)pendingLong=null;if(project.notes.length!==before){eraseChanged=true;renderNotes();updateEvents()}}
  function eraseAtPoint(x,y){const el=document.elementFromPoint(x,y)?.closest?.('.note');if(el&&els.wrap.contains(el))eraseById(el.dataset.id)}
  function startRange(e){const r=els.wrap.getBoundingClientRect();rangeDrag={x0:clamp(e.clientX-r.left,0,r.width),y0:clamp(e.clientY-r.top,0,r.height),x1:0,y1:0,additive:e.ctrlKey||e.shiftKey,base:new Set(selectedIds)};rangeDrag.x1=rangeDrag.x0;rangeDrag.y1=rangeDrag.y0;updateRangeBox()}
  function updateRangeBox(){if(!rangeDrag)return;const x=Math.min(rangeDrag.x0,rangeDrag.x1),y=Math.min(rangeDrag.y0,rangeDrag.y1),w=Math.abs(rangeDrag.x1-rangeDrag.x0),h=Math.abs(rangeDrag.y1-rangeDrag.y0);els.selectionBox.hidden=false;Object.assign(els.selectionBox.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`})}
  function finishRange(){if(!rangeDrag)return;const x0=Math.min(rangeDrag.x0,rangeDrag.x1),x1=Math.max(rangeDrag.x0,rangeDrag.x1),y0=Math.min(rangeDrag.y0,rangeDrag.y1),y1=Math.max(rangeDrag.y0,rangeDrag.y1),r=els.wrap.getBoundingClientRect(),h=r.height,w=r.width,next=rangeDrag.additive?new Set(rangeDrag.base):new Set();project.notes.forEach(n=>{const pts=notePoints(n),boxes=pts.map(p=>({l:p.lane/LANES*w,r:(p.lane+p.width)/LANES*w,t:h-tickToBottom(p.tick)-10,b:h-tickToBottom(p.tick)+10}));if(n.type==='long'){boxes.push({l:Math.min(...boxes.map(b=>b.l)),r:Math.max(...boxes.map(b=>b.r)),t:Math.min(...boxes.map(b=>b.t)),b:Math.max(...boxes.map(b=>b.b))})}if(boxes.some(b=>b.r>=x0&&b.l<=x1&&b.b>=y0&&b.t<=y1))next.add(n.id)});selectedIds=next;rangeDrag=null;els.selectionBox.hidden=true;renderNotes();toast(`${selectedIds.size}件を範囲選択しました`)}

  els.wrap.addEventListener('pointerdown',e=>{
    if(mode==='transfer')return;
    const noteEl=e.target.closest('.note');
    if(editTool==='eraser'){e.preventDefault();beginErase();if(noteEl)eraseById(noteEl.dataset.id);else eraseAtPoint(e.clientX,e.clientY);els.wrap.setPointerCapture?.(e.pointerId);return}
    if(editTool==='range'){e.preventDefault();startRange(e);els.wrap.setPointerCapture?.(e.pointerId);return}
    if(noteEl){e.preventDefault();const n=project.notes.find(x=>x.id===noteEl.dataset.id);if(!n)return;if(e.ctrlKey||e.shiftKey){toggleSelection(n.id);return}if(!selectedIds.has(n.id))selectOnly(n.id,false);if(editTool==='draw'){renderNotes();return}pushHistory();const part=noteEl.dataset.part;if(selectedIds.size>1){drag={kind:'group',startX:e.clientX,startY:e.clientY,originals:new Map(selectedNotes().map(x=>[x.id,deep(x)])),limits:groupLimits(selectedNotes())}}else{const p=n.type==='long'?n[part]:n;drag={kind:'point',id:n.id,part,startX:e.clientX,startY:e.clientY,orig:deep(p)}}noteEl.setPointerCapture?.(e.pointerId);renderNotes();return}
    if(editTool==='select'){if(!(e.ctrlKey||e.shiftKey))clearSelection();return}
    const p=createPointFromEvent(e,2);createNote(activeType,p,null);flashPoint(p)
  });
  window.addEventListener('pointermove',e=>{
    if(erasing){eraseAtPoint(e.clientX,e.clientY);return}
    if(rangeDrag){const r=els.wrap.getBoundingClientRect();rangeDrag.x1=clamp(e.clientX-r.left,0,r.width);rangeDrag.y1=clamp(e.clientY-r.top,0,r.height);updateRangeBox();return}
    if(!drag)return;const rect=els.wrap.getBoundingClientRect(),laneRaw=Math.round((e.clientX-drag.startX)/(rect.width/LANES)),tickRaw=Math.round((-(e.clientY-drag.startY)/project.measureHeight*TPM)/guideTick())*guideTick();if(drag.kind==='point'){const n=project.notes.find(x=>x.id===drag.id);if(!n)return;const p=n.type==='long'?n[drag.part]:n;p.lane=clamp(drag.orig.lane+laneRaw,0,LANES-p.width);p.tick=clamp(snapTick(drag.orig.tick+tickRaw),0,project.measures*TPM);normalizeNote(n)}else{const laneDelta=clamp(laneRaw,-drag.limits.minLane,LANES-drag.limits.maxLane),tickDelta=clamp(tickRaw,-drag.limits.minTick,project.measures*TPM-drag.limits.maxTick);for(const [id,orig] of drag.originals){const n=project.notes.find(x=>x.id===id);if(!n)continue;if(n.type==='long'){n.start=deep(orig.start);n.end=deep(orig.end);[n.start,n.end].forEach(p=>{p.lane+=laneDelta;p.tick=snapTick(p.tick+tickDelta)})}else{n.tick=snapTick(orig.tick+tickDelta);n.lane=orig.lane+laneDelta}normalizeNote(n)}}renderNotes()
  });
  window.addEventListener('pointerup',()=>{if(rangeDrag)finishRange();if(drag){drag=null;scheduleSave()}if(erasing){erasing=false;if(eraseChanged){scheduleSave();toast('消しゴムで削除しました')}eraseChanged=false}});
  function flashPoint(p){const f=document.createElement('div');f.className='snap-flash';f.style.left=`${(p.lane+p.width/2)/LANES*100}%`;f.style.bottom=`${tickToBottom(p.tick)}px`;els.layer.appendChild(f);setTimeout(()=>f.remove(),450)}

  function updateProperties(){const list=selectedNotes(),n=selected(),none=!list.length,multi=list.length>1;['#propType','#propMeasure','#propStep','#propLane','#propWidth'].forEach(s=>$(s).disabled=!n);['#duplicateBtn','#deleteBtn'].forEach(s=>$(s).disabled=none);$('.long-props').hidden=!n||n.type!=='long';$('#selectedIdText').textContent=none?'未選択':multi?`${list.length}件選択`:n.id.slice(0,8);$('#selectionSummary').textContent=none?'単選択または範囲選択でノーツを選択できます。':multi?`${list.length}件を選択中。譜面上でドラッグするとまとめて移動でき、複製・削除も一括で行います。`:'1件を選択中。位置・幅・種類を編集できます。';if(!n){['#propMeasure','#propStep','#propLane','#propWidth','#propRaw'].forEach(s=>$(s).value='');return}const p=noteStart(n),parts=tickParts(p.tick);$('#propType').value=n.type;$('#propMeasure').value=parts.measure;$('#propStep').max=project.guide;$('#propStep').value=parts.step;$('#propLane').value=p.lane;$('#propWidth').value=p.width;$('#propRaw').value=n.rawTime==null?'手動配置':`${Number(n.rawTime).toFixed(3)} s`;if(n.type==='long'){const ep=tickParts(n.end.tick);$('#endMeasure').value=ep.measure;$('#endStep').max=project.guide;$('#endStep').value=ep.step;$('#endLane').value=n.end.lane;$('#endWidth').value=n.end.width}}
  function applyProperties(){const n=selected();if(!n)return;pushHistory();const oldType=n.type;const newType=$('#propType').value;const base=deep(noteStart(n));base.tick=partsToTick($('#propMeasure').value,$('#propStep').value);base.lane=Number($('#propLane').value);base.width=Number($('#propWidth').value);n.type=newType;if(newType==='long'){n.start=base;n.end=oldType==='long'&&n.end?deep(n.end):deep(base);n.end.tick=partsToTick($('#endMeasure').value||tickParts(base.tick).measure,$('#endStep').value||tickParts(base.tick).step);n.end.lane=Number($('#endLane').value||base.lane);n.end.width=Number($('#endWidth').value||base.width);delete n.tick;delete n.lane;delete n.width}else{n.tick=base.tick;n.lane=base.lane;n.width=base.width;delete n.start;delete n.end}normalizeNote(n);renderAll();scheduleSave()}
  ['#propType','#propMeasure','#propStep','#propLane','#propWidth','#endMeasure','#endStep','#endLane','#endWidth'].forEach(s=>$(s).addEventListener('change',applyProperties));
  $('#deleteBtn').addEventListener('click',()=>{if(!selectedIds.size)return;pushHistory();project.notes=project.notes.filter(n=>!selectedIds.has(n.id));selectedIds.clear();pendingLong=null;renderAll();scheduleSave();toast('選択ノーツを削除しました')});
  $('#duplicateBtn').addEventListener('click',()=>{const list=selectedNotes();if(!list.length)return;pushHistory();const ids=[];list.forEach(n=>{const c=deep(n);c.id=uid();if(c.type==='long'){c.start.tick=snapTick(c.start.tick+guideTick());c.end.tick=snapTick(c.end.tick+guideTick())}else c.tick=snapTick(c.tick+guideTick());project.notes.push(normalizeNote(c));ids.push(c.id)});selectedIds=new Set(ids);renderAll();scheduleSave();toast(`${ids.length}件を複製しました`)});

  const capturePreset={
    tap:{lane:5,width:2},
    critical:{lane:2,width:2},
    flick:{lane:8,width:2},
    long:{lane:10,width:2}
  };
  function capture(type){if(!running)return;const raw=getCurrentTime();const tick=timeToTick(raw);const preset=capturePreset[type]||capturePreset.tap;const p={tick,lane:preset.lane,width:preset.width};if(type==='long'){if(!pendingLong){createNote('long',p,raw)}else createNote('long',p,raw)}else createNote(type,p,raw);scrollToTick(tick);flashPoint(p)}
  $$('.keyrow').forEach(row=>{const label=row.querySelector('span')?.textContent||'',key=row.querySelector('kbd');if(!key)return;if(label.includes('通常'))key.textContent='Space';else if(label.includes('黄色'))key.textContent='J';else if(label.includes('フリック'))key.textContent='F';else if(label.includes('ロング'))key.textContent='K'});
  window.addEventListener('keydown',e=>{
    if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
    if(e.code==='Space'){e.preventDefault();capture('tap')}else if(e.key.toLowerCase()==='j')capture('critical');else if(e.key.toLowerCase()==='f')capture('flick');else if(e.key.toLowerCase()==='k')capture('long');else if(e.key==='Backspace'){e.preventDefault();const last=project.notes.at(-1);if(last){pushHistory();project.notes.pop();if(last.id===pendingLong?.id)pendingLong=null;renderAll();scheduleSave()}}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='a'){e.preventDefault();selectedIds=new Set(project.notes.map(n=>n.id));renderNotes()}else if(e.key==='Delete'&&selectedIds.size){e.preventDefault();$('#deleteBtn').click()}else if(e.key==='Escape'){pendingLong=null;clearSelection()}else if(['1','2','3','4'].includes(e.key)){setEditTool({1:'draw',2:'select',3:'range',4:'eraser'}[e.key])}
  });